name: madarj
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  build_runner: ^2.4.9
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  device_info_plus: ^11.3.0
  device_preview: ^1.2.0
  dotted_border: ^2.1.0
  easy_localization: ^3.0.7
  file_picker: 8.3.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^14.1.1
  flutter_localization: ^0.2.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.2
  get_it: ^7.7.0
  intl_utils: ^2.8.8
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  local_auth: ^2.3.0
  location: ^7.0.0
  logger: ^2.4.0
  pdf_render: ^1.4.12
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.2
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  table_calendar: 3.1.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/images/bottom_nav/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
